#!/bin/bash
Green="\e[92;1m"
RED="\033[31m"
YELLOW="\033[33m"
BLUE="\033[36m"
FONT="\033[0m"
GREENBG="\033[42;37m"
REDBG="\033[41;37m"
OK="${Green}--->${FONT}"
ERROR="${RED}[ERROR]${FONT}"
GRAY="\e[1;30m"
NC='\e[0m'
red='\e[1;31m'
green='\e[0;32m'
DF='\e[39m'
Bold='\e[1m'
g="\033[1;92m"
y='\033[1;33m' #yellow
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[32m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
# Getting
clear
#IZIN SCRIPT
MYIP=$(curl -sS ipv4.icanhazip.com)
echo -e "\e[32mloading...\e[0m"
clear
# Valid Script
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/SETANTAZVPN/izinvps/ipuk/ip"
data_ip="https://abc.xcodehoster.com/izin"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      \033[0;36mTelegram${NC} t.me/MyridWan"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/6285279323958"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    exit
  fi
}
checking_sc
echo -e "\e[32mloading...\e[0m"
clear
#Domain
domain=$(cat /etc/xray/domain)

echo -e " ${y}  ┌───────────────────────────────┐$NC"
echo -e " ${y}  │${NC}${g}.::.${NC} OTHER SETTING MENU ${g}.::. $NC"
echo -e " ${y}  └───────────────────────────────┘$NC"
echo -e    "\033[1;33m  ┌──────────────────────────────────────────┐\033[0m"
echo -e "  ${y}│${NC}${g} 01.${NC}\033[0;36m Backup/Restor${NC}"
echo -e "  ${y}│${NC}${g} 02.${NC}\033[0;36m SPEEDTEST${NC}"
echo -e "  ${y}│${NC}${g} 03.${NC}\033[0;36m VPS INFO${NC}"
echo -e "  ${y}│${NC}${g} 04.${NC}\033[0;36m RESTART SERVICE${NC}"
echo -e "  ${y}│${NC}${g} 05.${NC}\033[0;36m REBOOT${NC}"
echo -e "  ${y}│${NC}${g} 06.${NC}\033[0;36m RUNNING SERVICE ${NC}"
echo -e "  ${y}│${NC}${g} 07.${NC}\033[0;36m CLEARLOG${NC}"
echo -e "  ${y}│${NC}${g} 08.${NC}\033[0;36m DELETE USER EXP${NC}"
echo -e "  ${y}│${NC}${g} 09.${NC}\033[0;36m EDIT BENNER${NC}"
echo -e "  ${y}│${NC}${g} 10.${NC}\033[0;36m CHANGE DOMAIN${NC}"
echo -e "  ${y}│${NC}${g} 11.${NC}\033[0;36m CERT SSL/DOMAIN${NC}"
echo -e "  ${y}│${NC}${g} 12.${NC}\033[0;36m INFO PORT${NC}"
echo -e "  ${y}│${NC}${g} 13.${NC}\033[0;36m AUTO REBOOT${NC}"
echo -e "  ${y}│${NC}${g} 14.${NC}\033[0;36m CLEAR CHACE${NC}"
echo -e "  ${y}│${NC}"
echo -e "  ${y}│${NC}${g} x.${NC}\033[0;36m Back To Menu ${NC}"
echo -e "\033[1;33m  └──────────────────────────────────────────┘\033[0m"
read -p "Select From Options [ 1 - 14 ] : " menu
echo -e ""
case $menu in
1)
    menu-backup
    ;;
2)
    speedtest
    ;;
3)
    gotop
    ;;
4)
    restart
    ;;
5)
    reboot
    ;;
6)
    run
    ;;
7)
    clear
    clearlog
    ;;
8)
    clear
    xp
    ;;
9)
    nano /etc/kyt.txt  
    ;;
10)
    addhost
    ;;    
11)
    fixcert
    ;;
12)
    clear
    prot
    ;;
13)
    autoreboot
    ;;
14)
    clear
    clearcache
    ;;
x)
    clear
    menu
    ;;
esac
